name: CI

on:
  push:
    branches:
      - main
  pull_request:

# Cancel previous workflows on previous push
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/actions/install

      - name: Build
        run: pnpm build

  biome:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/actions/install

      - name: check
        run: pnpm check

      - name: lint
        run: pnpm lint
      
      - name: Format
        run: pnpm format:check

      - name: Ensure no changes to git-tracked files
        run: git --no-pager diff --exit-code
  